### ISSUE TITLE
Missing usage of threat-sources in attack sceanrios for automatic rating

### ISSUE THREAD

**Issue by Helliosy** [SecSimon/TTM#1]
The Threat sources can not be added to the corresponding attack sceanarios as a drop down option which can be used for the risk assessment.

**Comment by SecSimon** [comment]
Thanks for your feedback. As this is mainly done in the automotive sector, I will add it as an option that can be activated in the settings. An update is coming soon.

**Comment by SecSimon** [comment]
I added the option in the latest release as mentioned above. 

A revision of the entire risk assessment is planned in the coming months. Let me know if you have any suggestions.
