### ISSUE TITLE
Feature Request: Use prettified JSON as savestate

### ISSUE THREAD

**Issue by hydraconis** [SecSimon/TTM#18]
For making collaboration without committing to Github (which might not be possible due to legal or contracting reasons), it would be nice if the savestate was changed as following:

- [ ] Prettify JSON
 This would greatly help when merging savestates. Currently, savestates do not really use lines. This is something that can be achieved using tools such as `sed`, but since large states of several MB are not easy to check for errors and consistency, this is something the user really wants to avoid. If the state used multiple lines, it would be much easier to diff states

- [ ] Do not use escapes for `"`. Currently, the savestate uses escapes for `"` Because of this, tools that are able to prettify, e.g. `jq` cannot do their magic. Therefore, another tactic would be to remove escapes so that the JSON is prettifiable.

**Comment by SecSimon** [comment]
This feature is implemented in [TTModeler Pro](https://emgarde.de)
