### ISSUE TITLE
Update install instructions for stand alone

### ISSUE THREAD

**Issue by Helliosy** [SecSimon/TTM#2]
list all dependencies for npm would be helpful

**Comment by SecSimon** [comment]
Do you mean two different things?

Do you want update instructions for the executable files? Where should I add these instructions, e.g. ReadMe? (it's actually just replacing the files, as their is no installer so far)

What do you mean with npm dependencies? You can get a first clue of the dependencies in the package.json file. Or do you mean a SBOM?

**Comment by Helliosy** [comment]
We had to use `npm install webpack` to conclude all dependencies for the development version.
Issue should be resolved.
