### ISSUE TITLE
Changes in Risk assessment view lead to deleted field in the Attack scenario changed

### ISSUE THREAD

**Issue by Helliosy** [SecSimon/TTM#3]
![image](https://github.com/SecSimon/TTM/assets/56081886/8f3b0d59-d813-48c4-9147-2195e966b683)
Change in the risk view drop down leads to a deleted field in the attack scenario view which results in error generating report. Screenshot the severity was changed and the attack scenario was opened afterwards.

**Comment by SecSimon** [comment]
Thanks for letting me know. This actually fixed another issues. An update is released.

**Comment by Helliosy** [comment]
Thank you.
