### ISSUE TITLE
Feature Request DFD Allow swapping sender and receiver

### ISSUE THREAD

**Issue by hydraconis** [SecSimon/TTM#4]
When the user draws a data flow, but later realizes, that the data flow is pointing in the wrong direction, it seems the only available option is to delete and redraw the data flow (apart from a cosmetic change of arrow direction).

It would be more convenient to allow swapping the direction. If the process of doing so would change or remove related data, a popup should notify the user about the changes triggered by the swap.

**Comment by hydraconis** [comment]
Furthermore, it would be good to have a way to redefine sender and receiver without needing to redraw the arrow

**Comment by hydraconis** [comment]
It would be nice to be able to change the magnet point (north,east,west,south) to which the arrow points, and to have 8-point magnet points (e.g. northwest, southeast). This is specifically interesting for more complex diagrams with many nodes and edges.

**Comment by SecSimon** [comment]
Thanks for your feedback! I will look at both features (swapping sender and receiver and 8 anchors) in the next days/weeks.
